$runningEventsUrl = "http://localhost:1470/api/runningevents"
$fieldEventsUrl = "http://localhost:1470/api/fieldevents"
$runningRelayEventsUrl = "http://localhost:1470/api/runningrelayevents"
$fieldRelayEventsUrl = "http://localhost:1470/api/fieldrelayevents"

Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"60M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"100M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"200M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"400M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"800M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"1600M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"3200M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"60M Hurdles","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"110M Hurdles","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"300M Hurdles","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"2K Steeple Chase","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 100M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 200M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 400M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 800M","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"60M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"100M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"200M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"400M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"800M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"1600M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"3200M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"60M Hurdles","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"110M Hurdles","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"300M Hurdles","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"2K Steeple Chase","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 100M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 200M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 400M","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningEventsUrl -Method Post -Body '{"Name":"Seated 800M","Gender":"Female"}' -ContentType "application/json"

Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x100M Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x200M Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x400M Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x800M Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x1600M Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"Sprint Medley","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"Distance Medley","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x110M Shuttle Hurdles","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x300M Shuttle Hurdles","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x100M Weight Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x100M Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x200M Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x400M Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x800M Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x1600M Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"Sprint Medley","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"Distance Medley","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x100M Shuttle Hurdles","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x300M Shuttle Hurdles","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $runningRelayEventsUrl -Method Post -Body '{"Name":"4x100M Weight Relay","Gender":"Female"}' -ContentType "application/json"

Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"High Jump","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Long Jump","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Pole Vault","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Shot Put","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Discus","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Hammer Throw","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Weight Throw","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Triple Jump","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Seated Shot Put","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"High Jump","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Long Jump","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Pole Vault","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Shot Put","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Discus","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Hammer Throw","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Weight Throw","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Triple Jump","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldEventsUrl -Method Post -Body '{"Name":"Seated Shot Put","Gender":"Female"}' -ContentType "application/json"

Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"High Jump Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Long Jump Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Pole Vault Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Shot Put Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Discus Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Hammer Throw Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Triple Jump Relay","Gender":"Male"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"High Jump Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Long Jump Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Pole Vault Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Shot Put Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Discus Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Hammer Throw Relay","Gender":"Female"}' -ContentType "application/json"
Invoke-RestMethod $fieldRelayEventsUrl -Method Post -Body '{"Name":"Triple Jump Relay","Gender":"Female"}' -ContentType "application/json"